### ISSUE TITLE
Download and build packages into ~/.hitch instead of project .hitch directory

### ISSUE THREAD

**Issue by crdoconnor** [hitchtest/hitchtest#1]
- To avoid the time re-downloading and re-building the same package for different projects.
- To save disk space.

**Comment by luzfcb** [comment]
I suggest using `~/.cache/hitch` instead of `~/.hitch`, and store there, only things that can be removed any time without problems, as the content that is currently in `.hitch/downloads` folder.

 `pip` uses `~/.cache/pip` to store cache

**Comment by crdoconnor** [comment]
Actually I think I'll just delete the downloads. There's no real need to keep them. I'll put built versions of python, postgres, redis, etc. in this directory which any test in any project can use rather than each project having its own builds. That way, if you used postgres 9.3.7 in one project, you won't have to download or build it if you try to use it in another.

It doesn't feel quite right to put installed software in a .cache directory somehow, even though in principle I guess it could be deleted without problems.

What do you think?

**Comment by crdoconnor** [comment]
Issue fixed by https://github.com/hitchtest/hitchtest/commit/4fbea7fb171234e4261989b8ebd7697dfd5fedfa in v0.7.2 of hitchtest and v0.3.1 of hitchpython. Packages are installed into ~/.hitchpkg directory.

Thanks for reporting.
