### ISSUE TITLE
Get email confirmation link url

### ISSUE THREAD

**Issue by Eraldo** [hitchtest/hitchtest#4]
How do I get the email confirmation link url from within a hitch test?

I took a look at this code..

``` python
        self.services['HitchSMTP'].logs.out.tail.until_json(
            lambda email: containing in email['payload'] or containing in email['subject'],
            timeout=25,
            lines_back=1,
        )
```

To get an idea.
However, This only checks but does not save information.
Any hint on how to make my test user click the sent email confirmation link url?

**Comment by Eraldo** [comment]
Never mind.. I solved it. :)

``` python
    def click_email_link(self, containing=None, link_text=None):
        """
        Click on a link in an email.
        :param containing: Text to search for to find the correct email.
        :param link_text: A text to be found in that link. [optional]
        :return:
        """
        email = self.services['HitchSMTP'].logs.out.tail.until_json(
            lambda email: containing in email['payload'] or containing in email['subject'],
            timeout=25,
            lines_back=1,
        )
        links = email['links']
        if link_text:
            for link in links:
                if link_text in link:
                    url = link
                    break
        else:
            url = links[0]
        self.driver.get(url)
```

**Comment by crdoconnor** [comment]
Yep. That looks about right :)

**Comment by Eraldo** [comment]
It does work. :)
If you have any suggestions on how to improve it - feel free to let me know.
(I love your response time by the way _smile_)

**Comment by crdoconnor** [comment]
For now this is good. A more ideal way would probably be for me to create a generic step library for receiving emails and then link to that in your engine.py.

I'm adding a ticket now to create one under hitchsmtp.

**Comment by crdoconnor** [comment]
Closing for now. Feel free to re-open if you have any other questions.
